branding:
  icon: activity
  color: gray-dark
name: 'Sync files'
description: 'This action syncs repository files with another repository.'
inputs:
  git-author-email:
    description: 'The email of the committer.'
    required: true
  git-author-name:
    description: 'The name of the committer.'
    required: true
  src-repository:
    description: ' The GitHub source repository.'
    required: true
  allow-files-pattern:
    description: 'The regex pattern for files that allowed to update. By default all files.'
    default: ".*"
  branch-name:
    descripion: 'The branch of the source repository to sync. By default master.'
    default: master
  exclude-files:
    description: 'Space-separated paths of files that should be excluded from sync.'
runs:
  using: "composite"
  steps: 
    - run: ${{ github.action_path }}/main.sh
      shell: bash
